name: build-artifact

on:
  pull_request:
    types:
      - labeled
      - synchronize
jobs:
  script-dependencies:
    if: contains(github.event.pull_request.labels.*.name, 'build')
    name: Updates Ontologies' JSON files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        shell: bash
        run: |
          python -m venv virtenv
          source virtenv/bin/activate
          pip install -r scripts/requirements.txt
      - name: Cache virtualenv
        uses: actions/cache@v3
        with:
          path: virtenv
          key: venv

  test-code:
    name: Test script
    runs-on: ubuntu-20.04
    needs: script-dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Restore virtualenv
        uses: actions/cache@v3
        with:
          path: virtenv
          key: venv
      - name: Test code
        shell: bash
        run: |
          source virtenv/bin/activate
          pytest scripts

  json-generation:
    name: Generate JSON files
    runs-on: ubuntu-20.04
    needs: test-code
    steps:
      - uses: actions/checkout@v3
      - name: Restore virtualenv
        uses: actions/cache@v3
        with:
          path: virtenv
          key: venv
      - name: Generate JSON files 
        shell: bash
        run: |
          source virtenv/bin/activate
          mkdir scripts/ontologies
          PYTHONPATH=scripts python scripts/ontoserpy/main.py ontologies.txt scripts/ontologies
      - name: Upload JSON files
        uses: actions/upload-artifact@v3
        with:
          name: ontologies
          path: ./scripts/ontologies

  frontend-dependencies:
    name: Install frontend dependencies
    runs-on: ubuntu-20.04
    needs: json-generation
    outputs:
        STORE_PATH: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        working-directory: ./frontend
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          key: pnpm
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm install --prod
  build:
    name: Build Svelte static site
    needs: frontend-dependencies
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Create directories
        working-directory: ./frontend
        shell: bash
        run: |
          mkdir ./src/lib/assets/ontologies
          mkdir ./static/public      
      - name: Download ontologies and move it to the directory
        uses: actions/download-artifact@v3
        with:
          name: ontologies
          path: ./frontend/src/lib/assets/ontologies
      - name: Create soft link to public directory
        working-directory: ./frontend/static/public
        shell: bash
        run: ln -s ../../src/lib/assets/ontologies/* .
      - name: Restore PNPM packages
        uses: actions/cache@v3
        with:
          key: pnpm
          path: ${{ needs.frontend-dependencies.outputs.STORE_PATH }}
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: true
      - name: Build
        working-directory: ./frontend
        shell: bash
        run: NODE_OPTIONS=--max-old-space-size=8192 npm build
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./frontend/build
