name: build-artifact

on:
  pull_request:
    types:
      - labeled
      - synchronize
jobs:
  pre-build:
    if: contains(github.event.pull_request.labels.*.name, 'build')
    name: Updates Ontologies' JSON files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        shell: bash
        run: |
          python -m venv virtenv
          source virtenv/bin/activate
          pip install -r scripts/requirements.txt
      - name: Test code
        run: pytest scripts
      - name: Generate JSON files 
        run: |
          mkdir ontologies
          PYTHONPATH=scripts python scripts/ontoserpy/main.py ontologies.txt scripts/ontologies

      - name: Upload JSON files
        uses: actions/upload-artifact@v3
        with:
          name: ontologies
          path: ./scripts/ontologies

  build:
    name: Build Svelte static site
    needs: pre-build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: ./frontend/pnpm-lock.yaml
      - name: Install dependencies
        working-directory: ./frontend
        shell: bash
        run: pnpm install
      - name: Create directory
        working-directory: ./frontend
        shell: bash
        run: mkdir ./src/lib/assets/ontologies
      - name: Download ontologies and move it to the directory
        uses: actions/download-artifact@v3
        with:
          name: ontologies
          path: ./frontend/src/lib/assets/ontologies
      - name: Create soft link to public directory
        working-directory: ./frontend/static/public
        shell: bash
        run: ln -s ../../src/lib/assets/ontologies/* .
      - name: Build
        working-directory: ./frontend
        shell: bash
        run: NODE_OPTIONS=--max-old-space-size=8192 pnpm build
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./frontend/build
