# Simple workflow for deploying static content to GitHub Pages
name: gh-pages

on:
  # Runs on push or pull_request merge targeting the default branch
  push:
    branches:
      - "main"
  schedule:
    - cron: "30 7 21 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  issues: write
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
    
jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    name: gh pages
    needs: build
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
