# Simple workflow for deploying static content to GitHub Pages
name: gh-pages

on:
  # Runs on push or pull_request merge targeting the default branch
  push:
    branches:
      - "main"
  schedule:
    - cron: "30 7 21 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  issues: write
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  pre-build:
    name: Updates Ontologies' JSON files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        shell: bash
        run: |
          python -m venv virtenv
          source virtenv/bin/activate
          pip install -r scripts/requirements.txt
      - name: Test code
        shell: bash
        run: pytest scripts
      - name: Generate JSON files 
        shell: bash
        run: |
          mkdir ontologies
          PYTHONPATH=scripts python scripts/ontoserpy/main.py ontologies.txt scripts/ontologies

      - name: Upload JSON files
        uses: actions/upload-artifact@v3
        with:
          name: ontologies
          path: ./scripts/ontologies
  notify-job:
    runs-on: ubuntu-20.04
    needs: pre-build
    name: Create failure issue
    if: ${{ failure() }}
    steps:
      - uses: actions/checkout@v3
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create-issue
      - run: "echo Created issue number ${{ steps.create-issue.outputs.number }}"
      - run: "echo Created ${{ steps.create-issue.outputs.url }}"

  build:
    name: Build Svelte static site
    needs: pre-build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: ./frontend/pnpm-lock.yaml
      - name: Install dependencies
        working-directory: ./frontend
        shell: bash
        run: pnpm install --prod
      - name: Create ontologies directory
        shell: bash
        run: mkdir ./frontend/src/lib/assets/ontologies
      - name: Download ontologies and move it to the directory
        uses: actions/download-artifact@v3
        with:
          name: ontologies
          path: ./frontend/src/lib/assets/ontologies
      - name: Create soft link to public directory
        working-directory: ./frontend/static/public
        shell: bash
        run: ln -s ../../src/lib/assets/ontologies/* .
      - name: Build
        working-directory: ./frontend
        shell: bash
        run: |
         NODE_OPTIONS=--max-old-space-size=8192 pnpm build
          touch ./build/.nojekyll
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./frontend/build
  deploy:
    name: gh pages
    needs: build
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
