# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - "feat/ci-cd"
  #   paths:
  #     - "static/public/**"
  # schedule:
  #   - cron: "30 7 21 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  issues: write
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  update-json:
    name: Updates Ontologies' JSON files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Generate JSON files
        shell: bash
        run: |
          output_dir="./frontend/src/lib/assets/ontologies"
          pip install -r ./scripts/requirements.txt
          python ./scripts/main.py ./scripts/input.txt $output_dir
          tar -cvf _ontologies $output_dir

      - name: Upload JSON files
        uses: actions/upload-artifact@v3
        with:
          name: ontologies-json-files
          path: _ontologies
      - name: Clean up
        shell: bash
        run: rm -v _ontologies

  notify-job:
    runs-on: ubuntu-20.04
    needs: update-json
    name: Create failure issue
    if: ${{ failure() }}
    steps:
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create-issue
      - run: "echo Created issue number ${{ steps.create-issue.outputs.number }}"
      - run: "echo Created ${{ steps.create-issue.outputs.url }}"

  deploy:
    name: Deploy Svelte APP
    needs: update-json
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: ./pnpm-lock.yaml
      - name: Install dependencies
        working-directory: ./frontend
        shell: bash
        run: pnpm install
      - name: Download ontologies and move it to the directory
        uses: actions/download-artifact@v3
        with:
          name: ontologies-json-files
      - name: Move ontologies to assets/ontologies
        shell: bash
        run: |
          output_file="./frontend/src/lib/assets/ontologies/_ontologies"
          mv ontologies-json-files $output_file
          tar -xvf $output_file
          rm -v $output_file
      - name: Build
        working-directory: ./frontend
        shell: bash
        run: |
          pnpm build
          touch ./build/.nojekyll
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload build repository
          path: "./frontend/build"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
